version: "3.8"
services:
  app:
    build: .
    depends_on:
      - bd
    ports:
      - "5000:5000"
    volumes:
      - ./src:/workdir/src
  bd:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
        - ./mongo-volume:/data/db